"""
Generated by claude...
Experiment B: Grid analysis of coupled diffusion across different prompt pairs and lambda values.

This experiment generates a comprehensive figure showing how coupled diffusion behaves
with different prompt combinations (rows) and coupling strengths (columns).

Usage:
    python experiment_b.py --output_dir ./outputs
    python experiment_b.py --prompt_pairs "a dog|a cat,a forest|a desert" --lambdas "0.0,0.05,0.1"
"""

import os
from argparse import ArgumentParser

import matplotlib.pyplot as plt
import numpy as np
import torch
from coupled_diff import (
    CoupledDiffusion,
    decode_latents_to_pil,
    retrieve_sd_pipeline,
)

# Default prompt pairs - diverse pairs to show coupling behavior
DEFAULT_PROMPT_PAIRS = [
    # Similar concepts - coupling should blend well
    ("a red sports car", "a blue sports car"),
    # Different styles of same subject
    ("a realistic photo of a cat", "a watercolor painting of a cat"),
    # Semantically different but visually compatible
    ("a sunny beach with palm trees", "a snowy mountain landscape"),
    # Abstract vs concrete
    ("a portrait of a young woman", "a portrait of an elderly man"),
]

# Default lambda values to test - from no coupling to strong coupling
DEFAULT_LAMBDAS = [0.0, 0.001, 0.005, 0.01, 0.015, 0.02]


def run_experiment(args, pipe_a, pipe_b):
    """
    Generate a grid figure showing the effect of different prompt pairs (rows)
    and lambda values (columns) on coupled diffusion.

    Each row shows results for a specific prompt pair across different lambdas.
    For each cell, we show both generated images (a and b) stacked vertically.
    """
    sampler = CoupledDiffusion(pipe_a, pipe_b)
    device = pipe_a.device
    dtype = pipe_a.unet.dtype

    # Get prompt pairs and lambdas
    prompt_pairs = args.prompt_pairs if args.prompt_pairs else DEFAULT_PROMPT_PAIRS
    lambdas = args.lambdas if args.lambdas else DEFAULT_LAMBDAS

    num_rows = len(prompt_pairs)
    num_cols = len(lambdas)

    print(f"Running Experiment B: {num_rows} prompt pairs x {num_cols} lambda values")
    print(f"Lambda values: {lambdas}")

    # Store all generated images
    # Structure: results[row_idx][col_idx] = (img_a, img_b)
    results = [[None for _ in range(num_cols)] for _ in range(num_rows)]

    # Generate images for each combination
    for row_idx, (prompt_a, prompt_b) in enumerate(prompt_pairs):
        print(f"\n--- Row {row_idx + 1}/{num_rows} ---")
        print(f"  Prompt A: {prompt_a}")
        print(f"  Prompt B: {prompt_b}")

        # Create consistent initial latents for this row (same noise across all lambdas)
        row_seed = args.seed + row_idx * 100
        init_a = CoupledDiffusion.make_initial_latents(
            pipe_a, 1, row_seed, device, dtype
        )
        init_b = CoupledDiffusion.make_initial_latents(
            pipe_b, 1, row_seed + 1, device, dtype
        )

        for col_idx, lambda_val in enumerate(lambdas):
            print(f"  Running lambda={lambda_val}...")

            latents_a, latents_b = sampler(
                prompt_a,
                prompt_b,
                lambda_=lambda_val,
                num_inference_steps=args.steps,
                guidance_scale=args.guidance_scale,
                seed_a=row_seed,
                seed_b=row_seed + 1,
                latents_a=init_a.clone(),
                latents_b=init_b.clone(),
            )

            img_a = decode_latents_to_pil(pipe_a, latents_a)[0]
            img_b = decode_latents_to_pil(pipe_b, latents_b)[0]
            results[row_idx][col_idx] = (img_a, img_b)

    # Create the composite figure
    print("\nCreating composite figure...")
    fig = create_grid_figure(results, prompt_pairs, lambdas)

    # Save figure
    output_path = os.path.join(args.output_dir, "experiment_b_grid.png")
    fig.savefig(output_path, dpi=150, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print(f"Saved figure to {output_path}")

    # Also save individual images for reference
    individual_dir = os.path.join(args.output_dir, "experiment_b_individual")
    os.makedirs(individual_dir, exist_ok=True)
    for row_idx, (prompt_a, prompt_b) in enumerate(prompt_pairs):
        for col_idx, lambda_val in enumerate(lambdas):
            img_a, img_b = results[row_idx][col_idx]
            img_a.save(
                os.path.join(individual_dir, f"row{row_idx}_lambda{lambda_val}_a.png")
            )
            img_b.save(
                os.path.join(individual_dir, f"row{row_idx}_lambda{lambda_val}_b.png")
            )

    print(f"Saved individual images to {individual_dir}/")


def create_grid_figure(results, prompt_pairs, lambdas):
    """
    Create a matplotlib figure with the grid layout:
    - Top: Lambda scale labels
    - Left margin: Prompt pair labels
    - Grid cells: Each cell shows image A (top) and image B (bottom) stacked
    """
    num_rows = len(prompt_pairs)
    num_cols = len(lambdas)

    # Get image dimensions from first result
    img_width, img_height = results[0][0][0].size

    # Figure layout parameters
    cell_width = img_width
    cell_height = img_height * 2 + 10  # Two images stacked with small gap
    left_margin = 650  # Space for prompt labels
    top_margin = 80  # Space for lambda labels
    padding = 10

    # Calculate figure size
    fig_width = left_margin + num_cols * (cell_width + padding) + padding
    fig_height = top_margin + num_rows * (cell_height + padding) + padding

    # Create figure with white background
    fig = plt.figure(figsize=(fig_width / 100, fig_height / 100), dpi=100)
    ax = fig.add_axes([0, 0, 1, 1])
    ax.set_xlim(0, fig_width)
    ax.set_ylim(0, fig_height)
    ax.axis("off")
    ax.set_facecolor("white")

    # Add lambda labels at the top
    for col_idx, lambda_val in enumerate(lambdas):
        x = left_margin + col_idx * (cell_width + padding) + cell_width / 2
        y = fig_height - top_margin + 25
        ax.text(
            x,
            y,
            f"λ = {lambda_val}",
            fontsize=25,
            ha="center",
            va="center",
            fontweight="bold",
        )

    # Add prompt labels and images for each row
    for row_idx, (prompt_a, prompt_b) in enumerate(prompt_pairs):
        # Calculate y position for this row (from top)
        row_y = fig_height - top_margin - row_idx * (cell_height + padding) - padding

        # Add prompt labels on the left
        label_x = 10
        label_y = row_y - cell_height / 2

        # Wrap prompts for display
        wrapped_a = wrap_text(f"A: {prompt_a}", max_chars=35)
        wrapped_b = wrap_text(f"B: {prompt_b}", max_chars=35)

        ax.text(
            label_x,
            label_y + 230,
            wrapped_a,
            fontsize=25,
            ha="left",
            va="center",
            color="#2E7D32",  # Green for prompt A
            fontweight="medium",
        )
        ax.text(
            label_x,
            label_y - 230,
            wrapped_b,
            fontsize=25,
            ha="left",
            va="center",
            color="#1565C0",  # Blue for prompt B
            fontweight="medium",
        )

        # Add images for each lambda value
        for col_idx in range(num_cols):
            img_a, img_b = results[row_idx][col_idx]

            # Calculate position for this cell
            cell_x = left_margin + col_idx * (cell_width + padding)
            cell_y = row_y - cell_height

            # Convert PIL images to numpy for matplotlib
            img_a_arr = np.array(img_a)
            img_b_arr = np.array(img_b)

            # Add image A (top of cell)
            extent_a = [
                cell_x,
                cell_x + img_width,
                cell_y + img_height + 10,
                cell_y + cell_height,
            ]
            ax.imshow(img_a_arr, extent=extent_a, aspect="auto")

            # Add image B (bottom of cell)
            extent_b = [cell_x, cell_x + img_width, cell_y, cell_y + img_height]
            ax.imshow(img_b_arr, extent=extent_b, aspect="auto")

            # Add thin border around cell
            rect = plt.Rectangle(
                (cell_x - 2, cell_y - 2),
                cell_width + 4,
                cell_height + 4,
                linewidth=1,
                edgecolor="#CCCCCC",
                facecolor="none",
            )
            ax.add_patch(rect)

    return fig


def wrap_text(text, max_chars=40):
    """Wrap text to fit within a maximum character width."""
    words = text.split()
    lines = []
    current_line = []
    current_length = 0

    for word in words:
        if current_length + len(word) + 1 <= max_chars:
            current_line.append(word)
            current_length += len(word) + 1
        else:
            if current_line:
                lines.append(" ".join(current_line))
            current_line = [word]
            current_length = len(word)

    if current_line:
        lines.append(" ".join(current_line))

    return "\n".join(lines)


def parse_prompt_pairs(prompt_pairs_str):
    """
    Parse prompt pairs from command line argument.
    Format: "prompt_a1|prompt_b1,prompt_a2|prompt_b2,..."
    """
    if not prompt_pairs_str:
        return None
    pairs = []
    for pair_str in prompt_pairs_str.split(","):
        parts = pair_str.split("|")
        if len(parts) == 2:
            pairs.append((parts[0].strip(), parts[1].strip()))
    return pairs if pairs else None


def parse_lambdas(lambdas_str):
    """
    Parse lambda values from command line argument.
    Format: "0.0,0.02,0.05,0.1,0.2"
    """
    if not lambdas_str:
        return None
    try:
        return [float(x.strip()) for x in lambdas_str.split(",")]
    except ValueError:
        return None


def main():
    parser = ArgumentParser(
        description="Experiment B: Grid analysis of coupled diffusion"
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="./experiment_3b_outputs",
        help="Directory to save output images and figure",
    )
    parser.add_argument(
        "--prompt_pairs",
        type=str,
        default=None,
        help="Prompt pairs. Format: 'prompt_a1|prompt_b1,prompt_a2|prompt_b2,...'",
    )
    parser.add_argument(
        "--lambdas",
        type=str,
        default=None,
        help="Lambda values. Format: '0.0,0.02,0.05,0.1,0.2'",
    )
    parser.add_argument(
        "--guidance_scale",
        type=float,
        default=7.5,
        help="Classifier-free guidance scale",
    )
    parser.add_argument(
        "--steps", type=int, default=100, help="Number of inference steps"
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=32,
        help="Base random seed (each row uses seed + row_idx * 100)",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="manojb/stable-diffusion-2-1-base",
        help="Hugging Face model ID for Stable Diffusion",
    )
    args = parser.parse_args()

    # Parse custom prompt pairs and lambdas if provided
    args.prompt_pairs = parse_prompt_pairs(args.prompt_pairs)
    args.lambdas = parse_lambdas(args.lambdas)

    # Create output directory
    os.makedirs(args.output_dir, exist_ok=True)

    # Load pipelines
    print("Loading Stable Diffusion pipelines...")
    pipe_a = retrieve_sd_pipeline(args.model)
    pipe_b = retrieve_sd_pipeline(args.model)

    # Run experiment
    run_experiment(args, pipe_a, pipe_b)


if __name__ == "__main__":
    main()
